[package]
title = "chem_sim_reactor"
version = "2.0.0"
description = "Simulate chemical reactions with high-fidelity in Omniverse using OpenUSD and PhysX. Includes LLM-driven backend integration."
category = "Example"
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
keywords = ["kit", "example", "extension"]
preview_image = "data/preview.png"
readme = "docs/README.md"
repository = "https://github.com/NVIDIA-Omniverse/kit-app-template"

[dependencies]
"omni.usd" = {}
"omni.physx" = {}
"omni.kit.viewport.window" = {}
"omni.kit.window.console" = {}
"omni.kit.window.extensions" = {}
"omni.kit.window.filepicker" = {}

[settings]

[[python.module]]
name = "heptre.chem_sim_reactor"

[python.pip]
packages = ["openai==0.27.9", "firebase-admin", "python-dotenv","pydantic==1.10.13"]


[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]

[[test]]
dependencies = []
args = []
